# Generated by Django 4.1 on 2023-10-24 07:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0009_alter_order_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customer",
            options={
                "ordering": ["user__first_name", "user__last_name"],
                "permissions": [("view_history", "Can view history")],
            },
        ),
        migrations.AlterField(
            model_name="customer",
            name="membership",
            field=models.CharField(
                choices=[("B", "Bronze"), ("S", "Silver"), ("G", "Gold")],
                default="B",
                max_length=1,
            ),
        ),
    ]
